name: Deploy Theme to Lightsail
on:
  push:
    branches: [staging, main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set Environment Variables
        run: |
          if [ "${{ github.ref }}" == "refs/heads/staging" ]; then
            echo "HOST=${{ secrets.STAGING_HOST }}" >> $GITHUB_ENV
            echo "KEY=${{ secrets.PRODUCTION_SSH_KEY }}" >> $GITHUB_ENV
          else
            echo "HOST=${{ secrets.PRODUCTION_HOST }}" >> $GITHUB_ENV
            echo "KEY=${{ secrets.PRODUCTION_SSH_KEY }}" >> $GITHUB_ENV
          fi

      - name: Deploy via SSH
        uses: appleboy/scp-action@master
        with:
          host: ${{ env.HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ env.KEY }}
          source: "./"
          target: "/opt/bitnami/wordpress/wp-content/themes/project-2025-tr1-jcua-team5"
